version: '3'

# container networks to set up
networks:
  django_db_net:
    external: false

# the containers to spin up
services:
  db:
    image: mariadb:latest
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=this_is_a_bad_password
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=autograder
    networks:
      - django_db_net

  django:
    build: ./docker/django
    restart: 'unless-stopped'
    depends_on:
      - db
    networks:
      - django_db_net
    volumes:
      - ./src:/src
    working_dir: /src/autograder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${DJANGO_PORT:-48000}:8000"
