# Generated by Django 3.0.5 on 2020-05-14 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gradebook.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give a name to the assignment.', max_length=60, unique=True)),
                ('description', models.TextField(help_text='Describe the assignment.', max_length=1000)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_grade_assignment', 'Is allowed to grade an assignment'), ('can_submit_assignment', 'Is allowed to turn in an assignment'), ('can_run_tests', 'Is allowed to run an assignment in a unit test')],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is the name of the test?', max_length=100)),
                ('description', models.TextField(help_text='Describe the parameters of the test.', max_length=1000)),
                ('test_file', models.FileField(upload_to='tests/', validators=[gradebook.validators.validate_file])),
                ('view', models.CharField(blank=True, choices=[('Viewable to all', 'Public'), ('Viewable to instructor', 'Private')], default='Private', help_text='Test View Permissions', max_length=50)),
                ('attached_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gradebook.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_name', models.CharField(help_text='Choose a name for your assignment', max_length=25)),
                ('submission_file', models.FileField(upload_to='submissions/', validators=[gradebook.validators.validate_file])),
                ('assignment', models.ManyToManyField(help_text='What assignment is this \t\t\t\t\t\t\t\t\t\t\t\t          submission for?', to='gradebook.Assignment')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_description', models.CharField(help_text='Write a brief description', max_length=60, unique=True)),
                ('full_description', models.TextField(help_text='Describe the project in full.', max_length=1000)),
                ('assigned_students', models.ManyToManyField(help_text='What students are assigned \t\t\t\t\t\t\t\t\t\t\t   to this project?', to=settings.AUTH_USER_MODEL)),
                ('assignment_list', models.ManyToManyField(help_text='What assignments are attached \t\t\t\t\t\t\t\t\t\t\t\t\t\t  to this project?', to='gradebook.Assignment')),
            ],
        ),
    ]
