# Generated by Django 3.0.5 on 2020-05-14 23:02

from django.db import migrations, models
import gradebook.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_auto_20200514_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='extra_file',
            field=models.FileField(blank=True, null=True, upload_to='src/', validators=[gradebook.validators.validate_file]),
        ),
    ]
